Zagrios/bs-manager

- src/renderer/components/shared/bsm-checkbox.component.tsx
replace 
Brignesst-50 by Opacity-30
> Update Required mods interface

- src/renderer/components/nav-bar/bs-version-item.component.tsx
fix issue [#7](https://github.com/Zagrios/bs-manager/issues/7)
> color for dark and light theme

- src/renderer/components/modal/modal-types/edit-version-modal.component.tsx
- src/renderer/components/modal/modal.component.tsx
- src/renderer/components/shared/bsm-button.component.tsx
fix issue [#6](https://github.com/Zagrios/bs-manager/issues/6)
> Bugfix/placeholder not visible light theme/6

- src/renderer/services/bs-launcher.service.ts
fix issue [#1](https://github.com/Zagrios/bs-manager/issues/1)
> not launch when lunch state is set

- .erb/configs/webpack.config.renderer.dev.ts
- .erb/configs/webpack.config.renderer.prod.ts
- postcss.config.js
- src/renderer/App.tsx
- tailwind.config.js
update tailwind setup by following guide here [https://electron-react-boilerplate.js.org/docs/styling](url)
> Update tailwind setup

- src/renderer/components/version-viewer/slides/mods/mod-item.component.tsx
fix issue #28 by using semver library
> bugfix/outdated mod not detected as outdate/28

- src/renderer/components/maps-mangement-components/filter-panel.component.tsx
- src/renderer/components/modal/modal-types/download-maps-modal.component.tsx
- src/renderer/hooks/use-behavior-subject.hook.ts
Add optionnal apply button, in maps filters panel
> bugfix/filter too complex to apply/59

- assets/jsons/translations/fr.json
J'ai corrigé la majorité des fautes que j'ai pu trouvé, ainsi que les problèmes de cohérence dans la mention du jeu. C'est à dire que des fois le jeu est appelé BeatSaber et des fois Beat Saber.
> Correction d'orthographe

- src/main/ipcs/beat-saver-ipcs.ts
- src/main/services/additional-content/local-maps-manager.service.ts
- src/main/services/bs-version-lib.service.ts
- src/main/services/ipc.service.ts
- src/main/services/supporters.service.ts
- src/main/services/thrid-party/beat-saver/beat-saver.service.ts
- src/main/services/utils.service.ts
- src/renderer/components/maps-mangement-components/filter-panel.component.tsx
- src/renderer/components/maps-mangement-components/local-maps-list-panel.component.tsx
- src/renderer/pages/version-viewer.component.tsx
- src/renderer/services/maps-manager.service.ts
- src/renderer/services/thrird-partys/beat-saver.service.ts
reduce by 40% the loading time of maps
> [bugfix] maps loding optimization (partial)

- assets/jsons/translations/de.json
The Whole Translation was written in "Du" so the new Changes need to be also written in "Du" and not in "Sie".
> Changed from "Sie" to "Du"

- assets/jsons/translations/en.json
"performances" should have been singular, but reworded to remove implication that it *will* increase performance when that is *not* the case for everyone.
> Change wording for a tad more accuracy / Fix typo.

- package.json
- release/app/package.json
- src/main/services/auto-updater.service.ts
- src/renderer/pages/settings-page.component.tsx
- src/renderer/services/auto-updater.service.ts
- src/renderer/windows/App.tsx
[closes TICKET-###](https://link-to-your-ticket)
|        |       |
| | | |
| --- | --- | --- |
| Blocking | 🔴 ❌ 🚨 | RED |
| Non-blocking | 🟡 💡 🤔 💭 | Yellow, thinking, etc |
| Praise | 🟢 💚 😍 👍 🙌 | Green, hearts, positive emojis, etc |
> Feature/add changelog modal/178 - Update Branch after test with auto update

- .github/workflows/lint.yaml
- .github/workflows/node.js.yaml
- package-lock.json
- package.json
- release/app/package-lock.json
This starts work on #265
Currently just starting with builds on all 3 major OS's
Look at PR state :D
| | | |
| --- | --- | --- |
| Blocking | 🔴 ❌ 🚨 | RED |
| Non-blocking | 🟡 💡 🤔 💭 | Yellow, thinking, etc |
| Praise | 🟢 💚 😍 👍 🙌 | Green, hearts, positive emojis, etc |
> Adding CI starts work on #265

- .github/workflows/sonarcloud.yml
- sonar-project.properties
More advanced code quality analysis with SonarCloud for #265
> [chore] add sonarcloud action

- .prettierignore
Without this it would try to format the release folder. Which would take a *very* long time.
This makes it so running prettier doesn't get stuck on the minified javascript in the release folder.
Run `npx prettier -w .` and it doesn't try to format the release folder.
With this merged, can you @Zagrios please run the formatter with  `npx prettier -w .` and commit it quickly?
Not doing it myself because it would cause an immense amount of merge conflicts that would need to be fixed if the PR doesn't get merged immediately.
You may have to tweak the prettier configuration to your liking though, as by default it seem to use 2 space indentation.
After this is done I would probably add prettier to CI.
**For reviewers: Emojis can be added to comments to call out blocking versus non-blocking …
> style: add .prettierignore

- src/main/services/oculus.service.ts
This fixes a startup exception on linux, due to attempted windows registry read.
The combination of this and #264 makes downloading songs error free on linux.
Currently I just skip Oculus library detection since there are very few oculus users on linux.
However, just in case somebody wants to know why it isn't working I left a log message.
I can also add a `// TODO` or we could also open a ticket, but I am lazy.
Open client on linux and observe lack of exception compared to master branch. …
> fix(linux): skip oculus library detection

- src/main/preload.ts
- src/renderer/components/modal/modal-types/share-folders-modal.component.tsx
- src/renderer/config/default-configuration.config.ts
- src/renderer/preload.d.ts
- src/renderer/services/maps-manager.service.ts
- src/renderer/services/version-folder-linker.service.ts
- src/shared/models/provider-platform.enum.ts
Not tested on linux but i'm pretty sure it fix the issue
> [bugfix-272] fix wrong folder separator for maps

- assets/jsons/translations/en.json
Made a bunch of changes to the word choice and phrasing across the board in the English translation file, primarily to reduce confusion. Also changed many minor things to add consistency between options.
> Change wording in English translation for consistency and clarity

- src/renderer/index.ejs
> [bugfix-289] Add title in index.ejs to prevent the window title to be wiped magically

- src/main/services/additional-content/local-maps-manager.service.ts
Use steam to reduce ram consumption and split maps to load into chunks to avoid hit the open file limit.
> [bugfix-276] Fix crashing when loading bunch of maps

- assets/jsons/translations/es.json
Fixed various spanish strings that made no sense in that context.
> Better spanish translations

- src/main/services/additional-content/local-maps-manager.service.ts
- src/main/services/additional-content/local-models-manager.service.ts
- src/main/services/additional-content/local-playlists-manager.service.ts
close #310 
(Was more a bug that an enhancement)
> [bugfix] one click install contents not goes in custom symlinks

- src/main/services/bs-launcher.service.ts
Prevent mods to be yeeted when UserData folder is linked
> [bugfix] Add no-yeet agrs to prevent mods to be yeeted

- assets/jsons/translations/de.json
- assets/jsons/translations/fr.json
- assets/jsons/translations/ru.json
Hello! J'ai corrigé les fautes d'orthographes que j'ai pu trouvé, rendu plus clair certains textes. Je suis loin d'être parfait en français, donc n'hésitez pas à mentionner si un changement ne semble pas bon.
J'ai aussi remarqué que le jeu était mentionné comme "BeatSaber" et "Beat Saber" de façon hasardeuse, j'avoue que ça m'a un peu perturbé alors j'ai standardisé le nom en tant que "Beat Saber" dans les langues où le soucis était présent.
Y'a aussi un anglicisme pas beau, "supporteur" est généralement utilisé pour désigner quelqu'un qui encourage une équipe (en tout cas je n'ai pas vu ce mot utilisé autre part). C'est + utilisé dans le domaine du sport qu'autre chose, j'ai pas trouvé d'équivalent, je tenais juste à pointer ce petit soucis. (Techniquement il y a "Contributeur" mais ça …
> fix spelling and standardize the name of the game

- README.md
[closes TICKET-###](https://link-to-your-ticket)
|        |       |
| Non-blocking | 🟡 💡 🤔 💭    | Yellow, thinking, etc               |
| Praise       | 🟢 💚 😍 👍 🙌 | Green, hearts, positive …
> Feature/update readme - Fix bug with Firefox

- assets/jsons/translations/de.json
- assets/jsons/translations/en.json
- assets/jsons/translations/es.json
- assets/jsons/translations/fr.json
- assets/jsons/translations/ja.json
- assets/jsons/translations/ru.json
- assets/jsons/translations/zh-tw.json
- assets/jsons/translations/zh.json
- src/renderer/components/maps-mangement-components/filter-panel.component.tsx
- src/renderer/components/maps-mangement-components/map-item.component.tsx
- src/renderer/index.css
- src/renderer/index.tsx
[closes TICKET-392](https://github.com/Zagrios/bs-manager/issues/392)
|![image](https://github.com/Zagrios/bs-manager/assets/40648115/c6f26ac5-48ab-408c-9902-46147cf98ba9)|![image](https://github.com/Zagrios/bs-manager/assets/40648115/9b87c9a9-d3e9-4539-b4a7-91f59a9e8184)|
|![image](https://github.com/Zagrios/bs-manager/assets/40648115/eba3b77e-6a7c-4497-adac-946f567915ef)![image](https://github.com/Zagrios/bs-manager/assets/40648115/28908dfc-1e47-4094-af50-20781c7ad11c)|![image](https://github.com/Zagrios/bs-manager/assets/40648115/91dade42-2c64-41be-9db0-959184266f88)![image](https://github.com/Zagrios/bs-manager/assets/40648115/13441b8e-1234-444d-acf1-be9bee0f76a1)![image](https://github.com/Zagrios/bs-manager/assets/40648115/f3a8233c-9dfb-404f-8ca2 …
> Feature/maps tooltips/392

- assets/jsons/translations/de.json
[closes issue-434](https://github.com/Zagrios/bs-manager/issues/434)
> fixed typo in german translation for map installation

- assets/jsons/patreons.json
- assets/jsons/translations/de.json
- release/app/package-lock.json
- release/app/package.json
- src/main/services/request.service.ts
- src/renderer/components/modal/modal-types/edit-version-modal.component.tsx
> [feature] Add reset button for name to version edit modal

- release/app/package-lock.json
- release/app/package.json
- src/main/services/bs-launcher/bs-launcher.service.ts
resvg-js is much more lightweight for the same thing, maybe even more fast
> [CHORE] migrate from sharp to resvg-js

- src/renderer/components/version-viewer/slides/mods/mods-slide.component.tsx
> [bugfix] Fix wrong mods shown for a BS version

- .github/workflows/build.yaml
I wanted to test a feature that wasn't released yet but also didn't want to setup the dev environment on my personal computer. So, I wrote a simple GH actions build workflow to build and package the electron executable for me.
Since GH Actions is free, I thought this would be a nice addition for future BSManager testers.
I made the build workflow automatically build all commits on the master branch. Ideally this can be set to all other branches too. After the electron package is built, it is stored inside a GitHub artifact. Note that these expire after 90 days.
> GitHub Actions Build Workflow

- src/main/services/mods/bs-mods-manager.service.ts
Reverts Zagrios/bs-manager#464
> Revert "[chore] use winhttp.dll to detect bsipa installation"

- package-lock.json
Fixes builds failing on Linux, and it crashing on startup
The same as https://github.com/Zagrios/bs-manager/pull/498
I found this NPM issue, which seems to be what we're running into here, although deleting the `node_modules` folder doesn't fix the issue for me - only manually adding it to the lock file does.
https://github.com/npm/cli/issues/4828
| ------------ | …
> Fix Linux build & crash on startup

- src/renderer/components/nav-bar/nav-bar-items/shared-nav-bar-item.component.tsx
- src/renderer/components/nav-bar/nav-bar.component.tsx
[closes TICKET-###](https://link-to-your-ticket)
|     ![tttt](https://github.com/user-attachments/assets/db9b61ab-929e-4c9d-9686-13c2d35e1343)| ![tttt](https://github.com/user-attachments/assets/026d8a24-83ad-471c-844e-aebcb59bd50a)      |
| Blocking     | 🔴 ❌ 🚨 …
> [bugfix] fix incorrect active state in shared nav bar item

- assets/jsons/translations/de.json
[closes TICKET-544](https://github.com/Zagrios/bs-manager/issues/544)
I updated the German language file with better translations. This includes:
- Consistency for the German words "Du" and "Sie" (informal/familiar vs formal version of *You*)
- Corrected some spelling mistakes, wrong plural forms of words, wrong conjugation of verbs
- Corrected words written in uppercase when they didn't need to be
- Fixed one word written as two (mostly a combination with "-" was needed)
- Added a period at the end of some sentences
- [Line 124](https://github.com/kgabriel-dev/bs-manager/blob/b620b11eb5f6c34e25275df6a1c32af4fbb227dd/assets/jsons/translations/de.json#L124) was translated in a wrong meaning, that is corrected now
(I want to clarify that even though this pull requests changes quit some …
> Improving the German language file

- .github/workflows/labeler.yaml
Used `regex matching` instead of github actions simple `contains` check.
> [chore] properly add correct label for linux

- src/main/helpers/fs.helpers.ts
> [bugfix-602] fix link playlists error

- src/main/services/additional-content/local-playlists-manager.service.ts
Closes #618
* fixed some issues with #616 on the bplistSource name change
> [bugfix-618] support json files for playlists

- src/renderer/config/default-configuration.config.ts
Linking DLC can cause a lot of issues
> [chore] remove DLC folder from default shared folders

- assets/jsons/translations/ko.json
- src/renderer/components/modal/modal-types/download-maps-modal.component.tsx
- src/renderer/components/modal/modal-types/models/download-models-modal.component.tsx
- src/renderer/components/modal/modal-types/playlist/download-playlist-modal/download-playlist-modal-header.component.tsx
> [Bugfix&Add-#641] Added kr translations | Text wrap bug and incorrect translation of "Curated"

- src/renderer/pages/settings-page.component.tsx
> [chore] Added beatleader icon to playlist oneclick setting + change tippys color

- assets/jsons/translations/de.json
- assets/jsons/translations/en.json
- assets/jsons/translations/es.json
- assets/jsons/translations/fr.json
- assets/jsons/translations/ja.json
- assets/jsons/translations/ko.json
- assets/jsons/translations/ru.json
- assets/jsons/translations/zh-tw.json
- assets/jsons/translations/zh.json
- src/renderer/components/modal/modal-types/bs-version-outdated-modal.component.tsx
- src/renderer/hooks/use-translation.hook.ts
- src/renderer/pages/available-versions-list.components.tsx
- src/renderer/services/i18n.service.ts
> [chore] Added a pre-download warning modal for outdated BS versions

- assets/jsons/translations/ko.json
Hope for Korean release :MaxwellCat:
> [Transation] Correction of awkward Korean :D

- assets/jsons/bs-versions.json
Update new recommended version.
> That was a quick recommendation change.

- src/renderer/components/version-viewer/slides/mods/mods-slide.component.tsx
> [bugfix] Mod dependencies are not always installed

- electron-builder.config.js
- src/__tests__/unit/os.test.ts
- src/main/helpers/os.helpers.ts
- src/main/services/bs-launcher/abstract-launcher.service.ts
- src/main/services/bs-launcher/steam-launcher.service.ts
- src/main/services/bs-version-lib.service.ts
- src/main/services/linux.service.ts
- src/main/services/static-configuration.service.ts
[Discord Post](https://discord.com/channels/1049624409276694588/1314040014958755941)
* Fixed an issue with isProcessRunning and getProcessName in os.helpers.ts to filter out the correct grep'ed process.
* Reused #577 logic for systems that uses readonly file system for there installation build of BSM
> [bugfix] fixed issues with NixOS

- assets/jsons/translations/de.json
- assets/jsons/translations/en.json
- assets/jsons/translations/es.json
- assets/jsons/translations/fr.json
- assets/jsons/translations/ja.json
- assets/jsons/translations/ko.json
- assets/jsons/translations/ru.json
- assets/jsons/translations/zh-tw.json
- assets/jsons/translations/zh.json
- src/main/ipcs/bs-version-download/bs-download-ipcs.ts
- src/main/main.ts
- src/main/services/bs-version-download/bs-oculus-downloader.service.ts
- src/main/services/bs-version-download/bs-steam-downloader.service.ts
- src/renderer/components/modal/modal-types/bs-downgrade/login-to-meta-modal.component.tsx
- src/renderer/pages/settings-page.component.tsx
- src/renderer/services/bs-version-download/oculus-downloader.service.ts
- src/shared/helpers/oculus.helpers.ts
- src/shared/models/ipc/ipc-routes.ts
> [chore] reimplement login with meta

- src/main/services/mods/bs-mods-manager.service.ts
Issue described in [discord](https://discord.com/channels/1049624409276694588/1324153634291978323) where custom mods (mods that are not in BeatMods / BadBeatMods) does not load the mod list properly.
> [hotfix] fix isue where querying mods with non-existent hash in BBM

- assets/jsons/translations/de.json
- assets/jsons/translations/en.json
- assets/jsons/translations/es.json
- assets/jsons/translations/fr.json
- assets/jsons/translations/it.json
- assets/jsons/translations/ja.json
- assets/jsons/translations/ko.json
- assets/jsons/translations/ru.json
- assets/jsons/translations/zh-tw.json
- assets/jsons/translations/zh.json
- src/main/ipcs/bs-launcher-ipcs.ts
- src/main/services/bs-launcher/bs-launcher.service.ts
- src/main/services/steam.service.ts
- src/renderer/components/modal/modal-types/create-launch-shortcut-modal.component.tsx
- src/renderer/components/modal/modal-types/download-maps-modal.component.tsx
- src/renderer/pages/version-viewer.component.tsx
- src/renderer/services/bs-launcher.service.ts
- src/shared/models/ipc/ipc-routes.ts
- src/shared/models/steam/shortcut.model.ts
> [feature] create steam shortcut

- src/renderer/components/version-viewer/slides/mods/mods-grid.component.tsx
- src/renderer/components/version-viewer/slides/mods/mods-slide.component.tsx
> [chore] move import mods button

- src/renderer/components/shared/bsm-checkbox.component.tsx
- src/renderer/components/version-viewer/slides/launch/launch-options-panel.component.tsx
- src/renderer/components/version-viewer/slides/launch/launch-slide.component.tsx
> [bugfix] fix light theming for launch mod buttons

- src/main/services/mods/bs-mods-manager.service.ts
Clear the IPA folder to remove outdated files from previous BSIPA versions, preventing potential crashes caused by conflicting BSIPA files when launching Beat Saber.
> [bugfix] clear the IPA folder when installing BSIPA

- assets/jsons/translations/de.json
- assets/jsons/translations/en.json
- assets/jsons/translations/es.json
- assets/jsons/translations/fr.json
- assets/jsons/translations/it.json
- assets/jsons/translations/ja.json
- assets/jsons/translations/ko.json
- assets/jsons/translations/ru.json
- assets/jsons/translations/zh-tw.json
- assets/jsons/translations/zh.json
- src/main/services/mods/beat-mods-api.service.ts
- src/main/services/mods/bs-mods-manager.service.ts
- src/renderer/components/version-viewer/slides/mods/mods-slide.component.tsx
- src/renderer/pages/version-viewer.component.tsx
- src/renderer/services/bs-mods-manager.service.ts
Show a notification when mods are outdated :
One outdated mod:
More than one outdated mod :
Additional changes in this PR:
- Fixed an issue where outdated mods remained marked as outdated until Beat Saber was launched
- Utilized the ability of the hashlookup route to handle multiple hashes for retrieving installed mods
> [feature] Outdated mods notification

- src/__tests__/unit/fs.helpers.test.ts
- src/main/helpers/fs.helpers.ts
- src/shared/helpers/error.helpers.ts
The size of files and folders is now checked before and after movement to ensure no data is lost
> [chore] Enhance folder linking reliability by ensuring file size consistency during content movement

- src/main/services/mods/bs-mods-manager.service.ts
Reported in [discord](https://discord.com/channels/1049624409276694588/1333936878700859503)
> [hotfix] fixed handling for filtering out mods to uninstall

- README.md
> [!WARNING]  
> **Merge this pr only when you release BSM V1.5 !**
> [Chore] update changelog

- src/renderer/components/modal/modal-types/link-contents-modal.component.tsx
- src/renderer/services/models-management/models-manager.service.ts
- src/renderer/services/playlists-manager.service.ts
Closes #770
Issue described in [discord](https://discord.com/channels/1049624409276694588/1334669252237590660)
LinkContentModal does not return any data. Just changed the return type and set keepContent to true.
> [bugfix] fix issue where playlist gets deleted when linked

- src/main/services/request.service.ts
> [hotfix] unable to load mods from beatmods

- src/main/main.ts
Change format to `YYYY-MM-DD_HH-MM-SS_v{VERSION}.log`
> [chore] updated log names to readable timestamp

- src/renderer/components/version-viewer/slides/mods/mod-item.component.tsx
> Fix BeatLeader out of control (UI)

- src/main/services/bs-launcher/oculus-launcher.service.ts
Issue described in [Discord](https://discord.com/channels/1049624409276694588/1359771444141097081)
> [bugfix] add system env to beat saber exe launch command for oculus

- src/main/services/mods/beat-mods-api.service.ts
- src/main/services/mods/bs-mods-manager.service.ts
- src/main/services/request.service.ts
* added more loading when loading mods
Issue described in [discord](https://discord.com/channels/1049624409276694588/1363416934816809090)
> [bugfix] fix mod loading by removing side effects

- src/main/services/mods/bs-mods-manager.service.ts
- src/renderer/components/version-viewer/slides/mods/mod-item.component.tsx
This error occurred every time when uninstalling a mod
Even if the mod has been successfully removed
> [bugfix] Fix uninstall mod error

- docs/wiki/Guides/Login/How-to-obtain-your-Oculus-Token/How-to-obtain-your-Oculus-Token.md
There are no entries in the Network tab until you reload the page.
> Press CTRL+R after opening developer tools

- src/renderer/components/version-viewer/slides/launch/launch-slide.component.tsx
Issue described in [discord](https://discord.com/channels/1049624409276694588/1374311641407160424)
* refactored the code to use hooks for readability
> [fix] custom mods should be appended on version page load

- src/main/services/mods/bs-mods-manager.service.ts
There's a reason why Mod Assistant and other installers are looking for the presence of `winhttp.dll` before executing IPA.exe. While I despise this executable and plan to remove it in a future update, if it is launched right after a game update and before the user launches the game, it will restore the backup of the previous game version and break the game as a result.
It is automatically run when needed by BSIPA itself and should not be run manually unless instructed otherwise.
There's no way currently to prevent this from happening when uninstalling BSIPA.
> [bugfix] prevent corruption of the game when installing BSIPA

- src/main/main.ts
closes #906
Should replace the app.getPath("home") value to $XDG_DATA_HOME or $HOME/.local/share.
> [feat-906] changed linux home directory to XDG_DATA_HOME

- assets/jsons/patreons.json
Automated daily update of Patreon supporters.
> [chore] update patreons.json
