Zagrios/bs-manager

- assets/jsons/translations/en.json
On the "Launch" page, there are currently three launch options:
- `Oculus Mod`
- `Desktop Mod`
- `Debug Mod`
In my opinion, these should be translated to "Mode" instead, at least in English. "Mod" implies that it's a separate third party modification, such as installing another DLL
All of these options come natively with the software (`-vrmode oculus` and `fpfc` come with the game, and `--verbose` comes with BSIPA)
> Change 'Mod' -> 'Mode' in english launch options

- package-lock.json
- package.json
- src/main/helpers/zip.helpers.ts
- src/main/services/mods/bs-mods-manager.service.ts
- src/main/services/request.service.ts
Now we download mod zip in buffer, all is done in memory (zip manipulations, hash, etc)
> [Hotfix] Make ERPERM error not possible when extracting mod zip

- package.json
When running `npm install`, it was failing to find the `@types/color` dependency.
Moving this dependency to `devDependencies` with the others fixed the issue.
| | | |
| --- | --- | --- |
| Blocking | 🔴 ❌ 🚨 | RED |
| Non-blocking | 🟡 💡 🤔 💭 | Yellow, thinking, etc |
| Praise | 🟢 💚 😍 👍 🙌 | Green, hearts, positive emojis, etc |
> Move @types/color to devDependencies

- src/main/services/bs-installer.service.ts
Currently, the `ctrlc-windows` package kills the download process when canceled.
This doesn't work on non-Windows systems, which this PR aims to fix.
This PR fixes the issue by only using the `ctrlc` package on Windows and using the normal `#kill` method on other operating systems, which send the appropriate `SIGTERM` signal to gracefully shutdown the process. 
The easiest way to test the change would be to start downloading a new version and cancel it part way through.
> 🔴 This change …
> Properly kill the download process on non-Windows systems

- src/main/services/steam.service.ts
Currently, the steam installation path is retrieved from the Windows registry.
This PR allows the application to get the correct installation directory on Linux.
When getting the installation path, a switch statement defines the path, depending on the operating system. On Windows, the path is retrieved the same as before. On Linux, it's retrieved from `~/.steam/steam`, which, to my knowledge, Steam will always create.
| | | |
| --- | --- | …
> Use the correct steam installation path on Linux

- src/main/ipcs/bs-version-ipcs.ts
Currently, when attempting to open the folder an instance is installed in, it runs a Windows command to open file explorer. This PR changes the behavior to work on all platforms.
Instead of executing a Windows command, Electron's `shell#openPath` method is used.
- Open the install folder of an instance.
| | | |
| --- | --- | --- |
| Blocking | 🔴 ❌ 🚨 | RED |
| Non-blocking | 🟡 💡 🤔 💭 | Yellow, thinking, etc |
| Praise | 🟢 💚 😍 👍 🙌 | Green, …
> Use the platform native file manager when opening instance folder

- src/main/helpers/fs.helpers.ts
- src/main/services/additional-content/local-maps-manager.service.ts
On linux only exactly Info.dat was matched, and many maps use different casing.
Fixes map downloads on linux.
This just gets all files, and finds info.dat by comparing lowercase strings.
Slightly inefficient on windows, but I think a consistent implementation is worth it.
Download random maps on linux, previously that would throw errors quickly, since the casing was wrong.
Now it works without issues.
I can remove the formatting changes, but it's a bit annoying since my IDE autoformats and I have to sleep.
I can make a PR with automatic formatting checks with prettier and eslint if that is of interest.
E.g: Praise, minor suggestions, or clarifying questions that don’t block merging the …
> fix(linux): search for info file case insensitively

- src/main/models/depot-downloader.class.ts
- src/main/services/bs-installer.service.ts
Fix :
```
Unhandled Exception Error: spawn C:\Users\user\AppData\Local\Programs\bs-manager\resources\assets\scripts\depot-downloader\DepotDownloader.exe ENOENT
at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
at onErrorNT (node:internal/child_process:476:16)
at processTicksAndRejections (node:internal/process/task_queues:82:21)
```
> [bugfix] Ensure BSInstances exist before running depotdownloader

- src/main/services/bs-installer.service.ts
Fixes the Depot Downloader not functioning on Linux.
This should be double-checked to ensure Windows compatibility is not affected.
Instead of directly invoking the exe, it will run the DLL through dotnet when Linux is detected.
- Try downloading a version of Beat Saber on Linux and Windows.
| …
> Fix Depot Downloader not working on Linux

- src/main/services/liv/liv.service.ts
As of 46eb8d0, when launching the application on Linux it would immediately crash due to there not being an implementation of `#isLivInstalled` for Linux.
To fix this, I've simply added a Linux implementation that always returns false.
Try launching the application at/after 46eb8d0 with and without this patch.
| ------------ | -------------- | …
> Skip Liv initialization on Linux

- src/main/services/bs-launcher/abstract-launcher.service.ts
- src/main/services/bs-version-download/bs-oculus-downloader.service.ts
- src/main/services/bs-version-download/bs-steam-downloader.service.ts
BS version page being downloaded was always recognized as a Steam version, preventing launching if it was an Oculus version
(The bug occurs if staying on the same BS version page during its download then launching it without having changed page)
> [bugfix] BS version page being downloaded was always recognized as a Steam version, preventing launching if it was an Oculus version

- src/main/services/mods/bs-mods-manager.service.ts
Fixes the inability to install mods under Linux due to BSIPA being executed with Windows-specific parameters.
Closes #440.
When running on Linux, BSIPA is now run with dotnet in a screen session. The screen session is a hack. However, it's required since BSIPA tries to move the console cursor, which doesn't exist in our environment, and crashes with an ArgumentOutOfRangeException before exiting. Running it in a screen session fixes this problem.
- Try installing mods on Linux
> 🔴 This …
> Fix BSIPA not running on Linux

- src/main/services/steam.service.ts
I see the v1.5.0 branch is what's currently active so I've targeted this PR to that. Let me know if you'd like it on master and I'll rebase.
This removes the forced skip of the elevated check for Steam on Linux.
Steam should never be running as admin on Linux, so defaulting to true doesn't make sense, and the existing isElevated check appears to be working correctly.
| …
> Fix Steam elevated check on Linux

- assets/jsons/translations/en.json
The changes below show a clearer sentence structure for outlying why users are required to input their credentials to download prior versions of Beat Saber, how their credentials are being used and ensuring users are aware that their Steam credentials are only being used through DepotDownloader. I found the previous translation to be poorly written with improper grammar, this should clear up confusions with future users.
All other translations if not properly worded by their translators for the Steam Credentials popup will need to be updated as well alongside or after this PR.
Build a new version with this PR and check the English translations within the Steam Credentials popup.
E.g: …
> Clearer English translation for Steam Credentials popup

- release/app/package-lock.json
When starting bs-manager on Linux, it crashes immediately since the resvg binary for all platforms other than x64-win32 aren't present.
I've added the x64 GNU/Linux binary to the package-lock.json, which fixes the issue for me.
I'm not sure if this is the best or even the correct way to fix this issue, so if there's a different way to go about this, please let me know.
- Build & start the application on Windows.
- Build & start the application on Linux.
> 🔴 This change will break …
> Fix Linux crash on startup

- .erb/configs/webpack.config.base.ts
[closes TICKET-546](https://github.com/Zagrios/bs-manager/issues/546)
Issue was that when **webpack** bundles the project and **[name].bundle.dev.js** was executed, `require('regedit-rs')` was being called, producing the error in the ticket.
Resolution was to exclude `regedit-rs` within the webpack config `external` property.
| ------------ | -------------- | …
> [bugfix] exclude regedit-rs on externals when webpack bundles it in linux

- src/renderer/components/title-bar/title-bar.component.tsx
Adds an window restore icon and displays it when the window is maximized.
| Non-blocking | 🟡 💡 🤔 💭    | Yellow, thinking, etc               |
| Praise       | 🟢 💚 😍 👍 🙌 | Green, hearts, positive emojis, etc |
> Add window restore icon

- src/main/services/mods/bs-mods-manager.service.ts
Custom version name breaks installing BSIPA mod in linux. Eg. version name is `1.29.1 (Test)`
```
1] 21:30:07.182 › START IPA PROCESS screen -dmS "BSIPA" dotnet /home/<username>/BSManager/BSInstances/1.29.1 (Test 1)/IPA.exe -n
[1] 21:30:07.198 › IPA process stderr /bin/sh: -c: line 1: syntax error near unexpected token `('
[1] /bin/sh: -c: line 1: `screen -dmS "BSIPA" dotnet /home/<username>/BSManager/BSInstances/1.29.1 (Test 1)/IPA.exe -n'
[1] 
[1] 21:30:07.199 › Ipa process exist with non 0 code 2
[1] 21:30:07.199 › Error: Unable to install BSIPA
[1]     at BsModsManagerService.installMods (/home/<username>/Desktop/Beat_Saber/bs-manager/.erb/dll/main.bundle.dev.js:149365:66)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) cannot-install-bsipa
``` …
> [bugfix] wrap dotnet cmdlet's path argument with double quotes for installing bsipa

- src/main/services/bs-version-lib.service.ts
- src/main/services/static-configuration.service.ts
Publish with linux and run the `.AppImage` build file. Following error log should not be visible anymore.
```
[2024-09-10 00:17:21.799] [error] Unhandled Exception UnhandledRejection Error: EROFS: read-only file system, open '/tmp/.mount_<any>/resources/assets/jsons/bs-versions.json'
at writeFileSync (node:fs:2368:20)
at updateLocalVersions (/tmp/.mount_<any>/resources/app.asar/dist/main/main.js:14:1151852)
at u.loadBsVersions (/tmp/.mount_<any>/resources/app.asar/dist/main/main.js:14:1152117)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at u.getAvailableVersions (/tmp/.mount_<any>/resources/app.asar/dist/main/main.js:14:1152212)
```
E.g: Praise, minor …
> [bugfix] use static config for version list in linux

- src/renderer/components/modal/modal.component.tsx
If the modal options is not defined the ff. error is reported. Just handled it in the code so that the check is done properly.
```
[2024-09-21 12:06:03.298] [error] [
[
"Uncaught TypeError: Cannot read properties of undefined (reading 'closable')",
'file:///C:/Users/<user>/AppData/Local/Programs/bs-manager/resources/app.asar/dist/renderer/renderer.js',
2,
2311860,
"Error: Cannot read properties of undefined (reading 'closable')"
]
]
```
Open the modal for downloading a BS Version.
> 🔴 …
> [bugfix] handle undefined modal options properly

- assets/jsons/translations/de.json
- assets/jsons/translations/en.json
- assets/jsons/translations/es.json
- assets/jsons/translations/fr.json
- assets/jsons/translations/ja.json
- assets/jsons/translations/ru.json
- assets/jsons/translations/zh-tw.json
- assets/jsons/translations/zh.json
- src/renderer/pages/settings-page.component.tsx
Should prompt a successful notification when user logouts. 
[closes TICKET-543](https://github.com/Zagrios/bs-manager/issues/543)
* Login to the app, or directly inject a username within the electronjs renderer.
```js
localStorage.setItem("STEAM-USERNAME", "<any username>");
```
* Go to the settings page and logout
* Notification should show.
**pages.settings.steam-and-oculus.logout-success:** Logout Successful
**notifications.settings.steam.success.titles.logout** seems to be unused. Maybe this can be removed.
E.g: Blocking feedback must be …
> [feat-543] added notification when logging out

- src/main/services/utils.service.ts
- src/main/services/window-manager.service.ts
Correctly point to icon images for both windows and linux
| Non-blocking | 🟡 💡 🤔 💭    | Yellow, thinking, etc               |
| Praise       | 🟢 💚 😍 👍 🙌 | Green, hearts, positive emojis, etc |
> [bugfix] show bsm icon properly

- src/main/services/bs-launcher/steam-launcher.service.ts
closes https://github.com/Zagrios/bs-manager/issues/585
Added SteamEnv=1 in environment variable when launching the `Beat Saber.exe` file
Download any song in BSManager with any unicode character. Sample maps to download:
* みにまむ - misterlihao
* ツユ - アンダーヒロイン - wangyufy
**Check if they are visible in game.**
_**Check if downloading maps in game will properly work as well.**_
|              |                | …
> [bugfix-585] fixed unicode song titles not showing in game

- .github/ISSUE_TEMPLATE/config.yml
To reduce trivial / non-complex issues to be posted as github issues.
_**NOTE: about wording is different on the commit**_
> [chore] added discord link in issue template

- src/main/ipcs/bs-playlist-ipcs.ts
- src/main/services/additional-content/local-playlists-manager.service.ts
Closes #614
* refactored to just use bplistSource each time it gets passed into another function
* removed unused songCache variable
NOTE: not yet tested on Windows
> [bugfix-614] handle bplist source string within readPlaylistFromSource

- src/renderer/components/version-viewer/slides/launch/launch-slide.component.tsx
Advanced launch args are no longer used when the input is closed.
The glow effect on the toggle button indicates whether the launch args are being used or not.
\+ no need for a `<motion/>` component here
> [bugfix-620] fix weird UX with advanced launch args

- src/main/services/bs-version-download/bs-steam-downloader.service.ts
- src/renderer/components/modal/modal-types/bs-downgrade/login-to-steam-modal.component.tsx
- src/renderer/services/bs-version-download/steam-downloader.service.ts
All errors from DepotDownloader were displayed as 'Unknown error' due to the serialization/deserialization of errors
\+ handle qr code errors in the login modal
> [bugfix] Fixed all errors from depotdownloader was unknown errors

- src/main/util.ts
If the path to the BSManager installation contained URL special characters, like `C:\User\My#User\..\bs-manager`
BSManager was unable to locate its files
> [bugfix] Unable to load bsm's files if path to bsm contain url special chars

- src/main/services/steam.service.ts
Closes #452 
Fixes issue of steam not launching when it is not already open. Also flatpak now launches Beat Saber as expected
> [bugfix-452] fix to "launch game when steam is not running" on linux

- src/renderer/config/default-configuration.config.ts
Change default sort order of beatsaver maps to Relevance
Obviously you want to see Latest maps initially but fun fact: If you don't supply a search parameter Relevance returns the latest maps.
It's a really awful user experience to see the Latest maps when searching for something unless you've specifically asked for that:
(I know these aren't app screenshots but it's the same search results)
> Set default beat saver map sort order to Relevance

- src/main/services/thrid-party/beat-saver/beat-saver-api.service.ts
External api requests should be made to the api.beatsaver.com subdomain.
> Use correct beatsaver api url

- .eslintrc.js
- .github/workflows/build.yaml
- .github/workflows/lint.yaml
- .github/workflows/node.js.yaml
- .github/workflows/release-linux.yaml
- README.md
- build/after-install.sh
- docs/wiki/Linux.md
- electron-builder.config.js
- electron-builder.ts
- package.json
- src/__tests__/unit/os.test.ts
- src/__tests__/utils.ts
- src/main/constants.ts
- src/main/helpers/os.helpers.ts
- src/main/services/bs-launcher/abstract-launcher.service.ts
- src/main/services/bs-launcher/oculus-launcher.service.ts
- src/main/services/bs-launcher/steam-launcher.service.ts
- src/main/services/bs-version-lib.service.ts
- src/main/services/linux.service.ts
- src/main/services/mods/bs-mods-manager.service.ts
- src/main/services/oculus.service.ts
- src/main/services/static-configuration.service.ts
- src/main/services/steam.service.ts
- src/renderer/components/modal/modal-types/setup/choose-proton-folder-modal.component.tsx
- src/renderer/pages/settings-page.component.tsx
Closes #627, Closes #468
- Already tested the `npm run publish:linux` and it should work on the ubuntu-latest
- Docs assumes that #586 is already merged
> [bugfix-627] build BSM with deb and flatpak for linux

- src/main/services/additional-content/local-playlists-manager.service.ts
Pass query parameters from playlist oneclick handler to the service that downloads the playlist.
`bsplaylist://playlist/https://api.beatsaver.com/playlists/id/12272/download?exp=1733163270&sig=db9ba0699986f368`
Currently this would be stripped to: `https://api.beatsaver.com/playlists/id/12272/download`
But after this change the exp and sig fields don't get removed and oneclick just works™️
| <img width="383" alt="Screenshot 2024-12-02 at 18 21 28" src="https://github.com/user-attachments/assets/4aaea5a0-f4fc-4209-be88-8689292d9963"> | <img width="427" alt="Screenshot 2024-12-02 at 18 26 03" src="https://github.com/user-attachments/assets/c1c07229-3741-4189-ab52-8f0dc19df3a4"> |
- Go to https://beatsaver.com
- Make a private playlist or bookmark a map …
> Pass query parameters to playlist downloader

- src/main/helpers/os.helpers.ts
Just used default `bash` rather than absolute `/bin/bash` to get the correct shell from all distros.
> [bugfix] change linux shell from /bin/bash to bash

- assets/jsons/translations/de.json
- assets/jsons/translations/en.json
- assets/jsons/translations/es.json
- assets/jsons/translations/fr.json
- assets/jsons/translations/ja.json
- assets/jsons/translations/ko.json
- assets/jsons/translations/ru.json
- assets/jsons/translations/zh-tw.json
- assets/jsons/translations/zh.json
- src/main/main.ts
- src/main/services/auto-updater.service.ts
- src/renderer/components/title-bar/title-bar.component.tsx
- src/renderer/services/auto-updater.service.ts
Since linux users update their application thru the package manager, disabled auto updates thru BSManager to not conflict or create issues with updates.
> [bugfix] remove auto update for linux builds

- .github/ISSUE_TEMPLATE/1-bug-report.yaml
- .github/ISSUE_TEMPLATE/config.yml
NOTE: Not sure if adding a separate field for log files is better than just having it being dropped in the addition content textarea field
**Rationale:** so we can force users to use the templates which has also have instruction on adding log files to reduce issue turn over time if possible.
> [chore] added instruction for adding logs in issue template

- assets/jsons/translations/de.json
- assets/jsons/translations/en.json
- assets/jsons/translations/es.json
- assets/jsons/translations/fr.json
- assets/jsons/translations/ja.json
- assets/jsons/translations/ko.json
- assets/jsons/translations/ru.json
- assets/jsons/translations/zh-tw.json
- assets/jsons/translations/zh.json
- src/main/services/bs-launcher/bs-launcher.service.ts
- src/main/services/linux.service.ts
- src/renderer/components/version-viewer/slides/launch/launch-mod-toogle.component.tsx
- src/renderer/components/version-viewer/slides/launch/launch-options-panel.component.tsx
- src/renderer/components/version-viewer/slides/launch/launch-slide.component.tsx
- src/renderer/services/i18n.service.ts
- src/shared/models/bs-launch/launch-option.interface.ts
Added a way write the proton logs within the BS version "Logs" folder.
As of https://github.com/Zagrios/bs-manager/pull/708/commits/6b5ccfe08b3b74819401e03d88e4dd6a7bfe4c10
**Texts**
proton-logs: Proton Logs
proton-logs-description: Enables the recording of proton logs for this Beat Saber install to "{versionPath}".
> [feat] add proton logs in advance launch settings for linux

- assets/jsons/translations/de.json
- assets/jsons/translations/en.json
- assets/jsons/translations/es.json
- assets/jsons/translations/fr.json
- assets/jsons/translations/ja.json
- assets/jsons/translations/ru.json
- assets/jsons/translations/zh-tw.json
- assets/jsons/translations/zh.json
- src/main/ipcs/static-configuration.ipcs.ts
- src/main/services/bs-launcher/bs-launcher.service.ts
- src/main/services/bs-local-version.service.ts
- src/main/services/static-configuration.service.ts
- src/renderer/services/bs-version-manager.service.ts
- src/renderer/services/static-configuration.service.ts
- src/renderer/windows/App.tsx
- src/shared/models/ipc/ipc-routes.ts
Feature request in [discord](https://discord.com/channels/1049624409276694588/1291894199683256320) regarding UX issues for new users.
* Changed labels "Select a version" to "Download a version" to not confuse new users if they are selecting their currently installed version.
> [feat] defaultly open to the last version launched on startup

- src/renderer/pages/version-viewer.component.tsx
Issue replication in [discord](https://discord.com/channels/1049624409276694588/1323382712345825370)
- Try to replicate with the discord, where they tried to verify their files but incorrectly passed a password.
- Try to invoke `navigate("/bs-version/<some version number>");` where you don't pass `{ state: version }` as the 2nd parameter.
> [bugfix] handle version view page if state/version becomes null

- electron-builder.config.js
- package.json
electron-builder [defaults to 20.08](https://www.electron.build/flatpak.html#baseversion) version of flatpak runtime and base packages. Those packages are EOL, here is example message from flatpak cli:
```
Info: runtime org.freedesktop.Platform branch 20.08 is end-of-life, with reason:
org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
```
I couldn't really find a source of truth for those messages, I suspect it just part of flatpak repository that can report if package is EOL
Manually specify versions for both runtime and base package. This will require to manually bump them later on, but it's just 2 lines of code change approximately every 2 years, so I hope that's not an issue =)
| ------ | …
> Update flatpak dependencies to non-EOL versions

- docs/wiki/Linux.md
**Future Notes**
Maybe creating a github hook would be good as well to bump the deb version for each release after 1.5.0 rolls out.
> [wiki] added deb install thru ppa repo in github

- src/renderer/components/version-viewer/slides/mods/mods-slide.component.tsx
Fixed an issue in the frontend where installedMods can contain a null element. Just removed the elements from the array.
> [hotfix] fix issue where installed mods are not reflected in mods tab

- electron-builder.config.js
Bug fix regarding to issue encountered in [discord](https://discord.com/channels/1049624409276694588/1325265216681803937)
Check if reinstalling the flatpak should add the `~/.steam/steam/steamapps/compatdata/620980:create` permission.
> [bugfix] allow compat folder create permission for linux flatpak

- src/main/services/linux.service.ts
- src/main/services/mods/bs-mods-manager.service.ts
Link #733 
The compatdata folder can exist outside of the steam `compatdata` folder. 
In theory of this as well, BS versions can have their on specific configs that doesn't affect every BS version, such as the UserData folder. However the space consumption can increase since the compatdata folder contains the windows OS files/directories.
Notes: you can also launch the game without downloading the steam version of the game, only for linux. Not sure if this can be done on Windows.
> [bugfix-733] custom compatdata folder for specific BSManager usage

- package.json
Make `LICENSE` and `package.json` consistent.
Set correct value in `package.json`.
N/A
N/A
| Non-blocking | 🟡 💡 🤔 💭    | Yellow, thinking, etc               |
| Praise       | 🟢 💚 😍 👍 🙌 | Green, hearts, positive emojis, etc |
> package.json: correct license value based on ./LICENSE

- src/__tests__/unit/fs.helpers.test.ts
- src/main/helpers/fs.helpers.ts
- src/main/main.ts
- src/main/services/additional-content/local-models-manager.service.ts
- src/main/services/additional-content/local-playlists-manager.service.ts
- src/main/services/additional-content/maps/local-maps-manager.service.ts
- src/main/services/folder-linker.service.ts
- src/main/services/mods/bs-mods-manager.service.ts
- src/main/services/request.service.ts
Issue from [discord](https://discord.com/channels/1049624409276694588/1334721659696971896)
When deleting a file or folder, log them so that it could be tracked in the logs file when checking for user errors.
Instead of using the direct function in fs, use there equivalent in fs.helpers module implementation.
unlink => deleteFile
unlinkSync => deleteFileSync
rm => deleteFolder
rmSync => deleteFolderSync
NOTE:
The wrapper function contains error codes without any resource, but they don't report anything on the frontend yet so didn't add it for now.
> [feat] added logs when deleting files/folders

- assets/jsons/translations/zh.json
[closes TICKET-798](https://github.com/Zagrios/bs-manager/issues/798)
Fix missing translation for the name of portguese (brazil) with chinese (simplified) language.
|![image](https://github.com/user-attachments/assets/5bd5549c-7b55-45b3-ad9b-758fc49f7df3)|![image](https://github.com/user-attachments/assets/8659461d-8b42-448c-96a0-286e198a9bed)|
- go to settings
- Select Chinese (simplified)
- check brazil …
> add missing translation in chinese (simplified)

- src/renderer/pages/settings-page.component.tsx
Relocation of the GitHub button to make it more visible and accessible (position and color chosen based on the current design of the BSManager.io website).
|![image](https://github.com/user-attachments/assets/3ef49b8d-9d66-4b3a-b1f5-42a80bf43aac)|![image](https://github.com/user-attachments/assets/70de5919-08f0-4037-84d5-1f061f27adec)|
|              |                | …
> move GitHub button in settings page

- src/main/services/folder-linker.service.ts
Issue described in [discord](https://discord.com/channels/1049624409276694588/1341644922771734618)
> [bugfix] use deleteFolder instead of deleteFile for linked folder paths

- src/main/models/oculus-downloader.class.ts
- src/main/services/bs-version-download/bs-oculus-downloader.service.ts
Closes #801 
Oculus uses backslashes `\` for file pathing in the manifest. Changed to forward slashes `/` for unix pathing support.
NOTE: Oculus + Linux is still unsupported.
> [bugfix-801] fixed issue when downloading oculus version in linux

- package-lock.json
The lockfile was missing some integrity hashes. The tool
npm-package-lock-add-resolved can help here.
See https://github.com/npm/cli/issues/4460
Ran `npx npm-package-lock-add-resolved`
Make sure `npm install` still works
| …
> [chore] Update lockfile integrity hashes

- docs/wiki/Guides/Installation-and-updates/install-bsmanager-on-linux/install-bsmanager-on-linux.md
Add NixOS/Nix section to the linux installation guide in the wiki, now that I've gotten a working package for bs-manager merged into nixpkgs.
> Add NixOS/Nix installation section in wiki

- src/main/services/additional-content/maps/local-maps-manager.service.ts
The regex for root map folders was broken, just extract the full zip instead.
> [bugfix] fix issue with extracting root map files

- src/renderer/components/version-viewer/slides/launch/launch-slide.component.tsx
`Launch options` button now only glow when unpinned options are enabled or if a command is present
> [chore] update GlowEffect visibility logic in LaunchSlide component

- src/main/services/bs-launcher/abstract-launcher.service.ts
Allow env vars to be overridden instead of being ignored, so that ie. Flatpak users can fix some invalid setting for the ENV_VARS like XAuthority
ref: [Discord](https://discord.com/channels/1049624409276694588/1329541144836571197)
> [bugfix] allow env overriding with launch options

- src/renderer/components/maps-playlists-panel/maps/local-maps-list-panel.component.tsx
Closes #634 
Issue also described in [discord](https://discord.com/channels/1049624409276694588/1373728798410805409)
Adjusted the correct height for the map item so that it could account for the padding y correctly.
EDIT: Although the gap spacing might not be to your liking, do we need to adjust it to something smaller?
> [fix/634] fixed issue on hovering on last song element

- src/renderer/components/settings/setting-radio-array.component.tsx
- src/renderer/pages/settings-page.component.tsx
With the number of languages supported by BSM increasing all the time, a small redesign of the display to divide everything into two columns makes it all look better :D 
|![image](https://github.com/user-attachments/assets/35d514c6-e0d2-4956-b898-a04614c9eb89)|![image](https://github.com/user-attachments/assets/2ab99be7-a916-4ba6-b831-ee2c39a21db9)![image](https://github.com/user-attachments/assets/f9b48f10-35a6-40df-bfa5-ca4764037102)|
- Clone my branch
- use `npm i` then `npm start`
- go settings
E.g: …
> Feature/language UI update

- src/main/services/mods/beat-mods-api.service.ts
- src/main/services/request.service.ts
~~Somewhat support ipv4, unlike the original implementation was to always check between the 2, let the user either use ipv6 (default) or force ipv4 in the settings.~~
Applied logic from https://github.com/Zagrios/bs-manager/pull/872#issuecomment-2954092281 insteadd
> [fix] use a caching method for ipv4/6 request calls

- src/renderer/components/modal/modal-types/download-maps-modal.component.tsx
Maps weren't loading when only a few remained.
> [bugfix] Fix "exclude installed" filter not loading more maps
